#### Finder 1phase kWh Meter 7E 64 8 230 0210 ####

modbus_controller:
  - id: Finder1
    ## Finder1 meter slaveadress 2
    address: 2
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    ## change parity frome even to none on the Finder meter. Baudrate to 9600
  - id: Finder2
    ## Finder2 meter slaveadress 3
    address: 3
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    ## change parity frome even to none on the Finder meter. Baudrate to 9600

sensor:
    ## Power1
  - platform: modbus_controller
    modbus_controller_id: Finder1
    name: Finder1 Power
    register_type: read
    address: 4134
    value_type: FP32
    unit_of_measurement: W
    state_class: "measurement"
    device_class: "power"
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Energy1
  - platform: modbus_controller
    modbus_controller_id: Finder1
    name: Finder1 Total Energy
    register_type: read
    address: 4358
    value_type: FP32
    unit_of_measurement: kWh
    state_class: "total_increasing"
    device_class: "energy"
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

    ## Power2
  - platform: modbus_controller
    modbus_controller_id: Finder2
    name: Finder2 Power
    register_type: read
    address: 4134
    value_type: FP32
    unit_of_measurement: W
    state_class: "measurement"
    device_class: "power"
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Energy2
  - platform: modbus_controller
    modbus_controller_id: Finder2
    name: Finder2 Total Energy
    register_type: read
    address: 4358
    value_type: FP32
    unit_of_measurement: kWh
    state_class: "total_increasing"
    device_class: "energy"
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    