#### Eastron SDM 3phase kWh Meter ####
## to add a SDM Modbus kWh meter reading, see https://gathering.tweakers.net/forum/list_message/77182598#77182598
modbus_controller:
  - id: SDM
    ## SDM meter slaveadress 5
    address: 5
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    parity: none  ## change frome even to none on the SDM meter

sensor:
    ## Power
  - platform: modbus_controller
    modbus_controller_id: SDM
    name: SDM Total System Power
    register_type: read
    address: 0x0034
    value_type: FP32
    unit_of_measurement: W
    state_class: "measurement"
    device_class: "power"
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM
    name: SDM Import Active Energy
    register_type: read
    address: 0x0048
    value_type: FP32
    unit_of_measurement: kWh
    state_class: "total_increasing"
    device_class: "energy"
    accuracy_decimals: 3
    
   # Current
  - platform: modbus_controller
    modbus_controller_id: SDM
    name: SDM Phase 1 Current
    register_type: read
    address: 0x0006
    value_type: FP32
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
    accuracy_decimals: 3

  - platform: modbus_controller
    modbus_controller_id: SDM
    name: SDM Phase 2 Current
    register_type: read
    address: 0x0008
    value_type: FP32
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
    accuracy_decimals: 3
    
  - platform: modbus_controller
    modbus_controller_id: SDM
    name: SDM Phase 3 Current
    register_type: read
    address: 0x000A
    value_type: FP32
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
    accuracy_decimals: 3