sensor:
    ## Temperature Setpoint – Zone 2 (signed) (FC4: 42, MA: 30043)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: temperature_setpoint_zone_2
    name: ${temperature_setpoint_zone_2}
    icon: mdi:home-thermometer
    address: 42
    device_class: temperature
    unit_of_measurement: "°C"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    state_class: "measurement"
    filters:
      - multiply: 0.01

    ## Flow Temperature Setpoint – Zone 2 (signed) (FC4: 46, MA: 30047)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: flow_temperature_setpoint_zone_2
    name: ${flow_temperature_setpoint_zone_2}
    icon: mdi:thermometer-auto
    address: 46
    device_class: temperature
    unit_of_measurement: "°C"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    state_class: "measurement"
    filters:
      - multiply: 0.01

    ## Room Temperature – Zone 2 (signed) (FC4: 54, MA: 30054)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: room_temperature_zone_2
    name: ${room_temperature_zone_2}
    icon: mdi:home-thermometer
    address: 54
    device_class: temperature
    unit_of_measurement: "°C"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    state_class: "measurement"
    filters:
      - multiply: 0.01

    ## Flow Temperature – Zone 2 (signed) (FC4: 70, MA: 30071)
#  - platform: modbus_controller
#    modbus_controller_id: ${name}
#    id: flow_temperature_zone_2
#    name: ${flow_temperature_zone_2}
#    icon: mdi:thermometer-auto
#    address: 70
#    device_class: temperature
#    unit_of_measurement: "°C"
#    register_type: read
#    value_type: S_WORD
#    accuracy_decimals: 1
#    state_class: "measurement"  
#    filters:
#      - multiply: 0.01

    ## Return Temperature – Zone 2 (signed) (FC4: 72, MA 30073)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: return_temperature_setpoint_zone_2
    name: ${return_temperature_setpoint_zone_2}
    icon: mdi:thermometer
    address: 72
    device_class: temperature
    unit_of_measurement: "°C"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    state_class: "measurement"  
    filters:
      - multiply: 0.01

number:
    ## H/C Thermostat Target Temperature – Zone 2 (signed) (FC6: 34, MA: 40035)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: hc_thermostat_target_temperature_zone_2
    name: ${hc_thermostat_target_temperature_zone_2}
    device_class: temperature
    icon: mdi:home-thermometer
    address: 34
    unit_of_measurement: "°C"
    step: 0.5
    register_type: holding
    value_type: S_WORD
    min_value: 10
    max_value: 36
    multiply: 100

    ## Thermostat Target Temperature – Zone 2 (signed) (FC6: 56, MA: 40057)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: thermostat_target_temperature_zone_2
    name: ${thermostat_target_temperature_zone_2}
    device_class: temperature
    icon: mdi:home-thermometer
    address: 56
    unit_of_measurement: "°C"
    step: 0.5
    register_type: holding
    value_type: S_WORD
    min_value: 10
    max_value: 36
    multiply: 100

switch:
    ## Cooling On Prohibit – Zone 2 (FC6: 43, MA: 40044)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: cooling_on_prohibit_zone_2
    name: ${cooling_on_prohibit_zone_2}
    register_type: holding
    icon: mdi:block-helper
    address: 43
    bitmask: 1
    entity_category: config

select:
    ## A/C mode – Zone 2 (FC6: 29, 40030)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: ac_mode_zone_2
    name: ${ac_mode_zone_2}
    address: 29
    optionsmap:
      ${heating_room}: 0
      ${heating_flow}: 1
      ${heating_curve}: 2
      ${cooling_room}: 3
      ${cooling_flow}: 4
      ${floor_dryup}: 5
    entity_category: config
